--liquibase formatted sql

--changeset bizin:1
CREATE TABLE dog(
                    dog_id BIGINT generated by default as identity primary key,
                    nick_name TEXT NOT NULL,
                    birth_year INT NOT NULL,
                    gender TEXT NOT NULL,
                    color TEXT NOT NULL,
                    species TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    id_user BIGINT
);

--changeset bizin:2
CREATE TABLE cat(
                    cat_id BIGINT generated by default as identity primary key,
                    nick_name TEXT NOT NULL,
                    birth_year INT NOT NULL,
                    gender TEXT NOT NULL,
                    color TEXT NOT NULL,
                    species TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    id_user BIGINT
);

--changeset bizin:3
CREATE TABLE owner(
    id BIGINT generated by default as identity primary key,
    chat_id BIGINT NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT,
    status TEXT,
    finish DATE,
    cat_id BIGINT,
    dog_id BIGINT
);

--changeset bizin:4
CREATE TABLE user_report(
                            id BIGINT generated by default as identity primary key,
                            id_user BIGINT NOT NULL,
                            changes TEXT NOT NULL,
                            report_date TIMESTAMP NOT NULL,
                            photo bytea NOT NULL
);
