--liquibase formatted sql

--changeset bizin:1
CREATE TABLE saved_users(
                            id BIGINT generated by default as identity primary key,
                            phone TEXT NOT NULL,
                            chat_id BIGINT NOT NULL,
                            time TIMESTAMP NOT NULL
);

--changeset bizin:2
CREATE TABLE dog(
                    id BIGINT generated by default as identity primary key,
                    nickName TEXT NOT NULL,
                    birth_year INT NOT NULL,
                    gender TEXT NOT NULL,
                    color TEXT NOT NULL,
                    species TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    id_dog_owner BIGINT NOT NULL
);

--changeset bizin:3
CREATE TABLE cat(
                    id BIGINT generated by default as identity primary key,
                    nickName TEXT NOT NULL,
                    birth_year INT NOT NULL,
                    gender TEXT NOT NULL,
                    color TEXT NOT NULL,
                    species TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    id_cat_owner BIGINT NOT NULL
);