--liquibase formatted sql

--changeset bizin:1
CREATE TABLE saved_users(
                            id BIGINT generated by default as identity primary key,
                            phone TEXT NOT NULL,
                            chat_id BIGINT NOT NULL,
                            time TIMESTAMP NOT NULL
);